on: [push, pull_request]

name: Build binaries

jobs:
  build-binaries:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build go
      run: go build .
    - name: Publish binaries
      uses: ncipollo/release-action@v1
      if: github.ref == 'refs/heads/master'
      with:
        allowUpdates: true
        removeArtifacts: true
        files: validator
        name: latest
        tag: latest
        body: "64-bit linux binary for the validator."
